# Generated by Django 4.1.7 on 2023-04-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, null=True, unique=True, verbose_name="email"
            ),
        ),
    ]
