# Generated by Django 4.1.7 on 2023-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0003_record_guess1_record_guess2_record_guess3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="guess1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess3",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess4",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess5",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess6",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
