# Generated by Django 4.1.7 on 2023-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0004_alter_record_guess1_alter_record_guess2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="guess1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess3",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess4",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess5",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="guess6",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
